# Generated by Django 5.2 on 2025-05-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_analysis', '0002_question_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('code', 'Code')], default='mcq', max_length=50),
            preserve_default=False,
        ),
    ]
